;###
;# Copyright (C) 2026 Sony Corporation
;#
;# Licensed under the Apache License, Version 2.0 (the "License");
;# you may not use this file except in compliance with the License.
;# You may obtain a copy of the License at
;#
;#      http://www.apache.org/licenses/LICENSE-2.0
;#
;# Unless required by applicable law or agreed to in writing, software
;# distributed under the License is distributed on an "AS IS" BASIS,
;# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;# See the License for the specific language governing permissions and
;# limitations under the License.
;###

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Templates/Template_Default.Template_Default

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/mocopi")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_Blank",NewGameName="/Script/mocopi")
+ActiveClassRedirects=(OldClassName="TP_BlankGameModeBase",NewClassName="mocopiGameModeBase")

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=722105644B525A6E0FB7E692AD9FB16E

bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=


[Internationalization]
#+LocalizationPaths=%GAMEDIR%Plugins/MocopiLiveLink/Localization
#+LocalizationPaths=%GAMEDIR%Plugins/MocopiLiveLink/Localization

[Core.Log]
LogLocalization:Display=Yes
LogLocalization:Warning=Yes
LogLocalization:Error=Yes

