;###
;# Copyright (C) 2026 Sony Corporation
;#
;# Licensed under the Apache License, Version 2.0 (the "License");
;# you may not use this file except in compliance with the License.
;# You may obtain a copy of the License at
;#
;#      http://www.apache.org/licenses/LICENSE-2.0
;#
;# Unless required by applicable law or agreed to in writing, software
;# distributed under the License is distributed on an "AS IS" BASIS,
;# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;# See the License for the specific language governing permissions and
;# limitations under the License.
;###

[/Script/UnrealEd.EditorPerformanceSettings]
bShowFrameRateAndMemory=False
bThrottleCPUWhenNotForeground=False
bDisableRealtimeViewportsInRemoteSessions=True
bMonitorEditorPerformance=False
bEnableSharedDDCPerformanceNotifications=True
bEnableScalabilityWarningIndicator=True
r.Editor.Viewport.HighDPI=True
r.Editor.Viewport.OverridePIEScreenPercentage=True
RealtimeScreenPercentageMode=ProjectDefault
NonRealtimeScreenPercentageMode=ProjectDefault
bOverrideManualScreenPercentage=False
ManualScreenPercentage=100.000000
bOverrideMinViewportRenderingResolution=False
MinViewportRenderingResolution=720
bOverrideMaxViewportRenderingResolution=False
MaxViewportRenderingResolution=2160

[/Script/UnrealEd.ContentBrowserSettings]
NumObjectsToLoadBeforeWarning=20
bOpenSourcesPanelByDefault=False
RealTimeThumbnails=True
DisplayFolders=True
DisplayEmptyFolders=True
FilterRecursively=True
bShowAllFolder=True
bOrganizeFolders=True
bDisplayContentFolderSuffix=True
bDisplayFriendlyNameForPluginFolders=True
NumObjectsInRecentList=20
bEnableRealtimeMaterialInstanceThumbnails=True
DisplayEngineFolder=False
DisplayDevelopersFolder=False
DisplayL10NFolder=False
DisplayPluginFolders=True
DisplayFavorites=False
DockCollections=True
DisplayCppFolders=True
IncludeClassNames=True
IncludeAssetPaths=True
IncludeCollectionNames=True

